### ISSUE TITLE
Be able work with in-memory strings / streams.

### ISSUE THREAD

**Issue by osher** [niiknow/text-file-diff#2]
It would be great if we could work with in-memory strings / streams.
What if there is no actual file on the fs?

I believe it could be accomplished by abstracting away the source of the strings from the work on them.

**Comment by noogen** [comment]
Thanks for the interest.  This library depends on `n-readlines` node module, which can process file input synchronously.  The original requirement was to compare large/multi-gigs file export for diff and can also manipulate/process changes on-the-fly.  At the time, 'n-readlines' node module was the best way to get this accomplished.  It also keep this library small and with only one dependency.

With async/await introduction in node 7.6+, it's now possible to use node internal `readline` node module synchronously for this.  Example:

```js
const readline = require('readline');

async function asyncLineByLine(readStream, callback) {
  const rl = readline.createInterface({
      input: readStream,
      crlfDelay: Infinity
  });

  for await(const line of rl) {
    await callback(line);
  }
}

const readStream1 = fs.createReadStream(filename);

// read line by line synchronously with await
await asyncLineByLine(readStream1, async (line1) => {
   // do your line 2 readline and comparison logic here...
});
```

With that in mind, I want to point out that large text file compare is what make this library unique.  At the time of researching/creating this library, there wasn't anything similar/available on on npm package.  On the hand, string/text diff are 'a dime a dozen'/easy to find.  

- https://www.npmjs.com/search?q=diff
- https://www.npmjs.com/search?q=text%20diff
- https://www.npmjs.com/search?q=string%20compare

I'm hesitant to make changes when there are many available options out there that does string comparison.  If you simply need string/text diff, you can just use the synchronous readline with `Symbol.asyncIterator` and any other diff library or simply `let result = line1 > line2 ? 1 : (line1 < line2 ? -1 : 0);` Example:

```js
// pseudo code
const rl1 = readline.createInterface({
  input: readStream1,
  crlfDelay: Infinity
})(Symbol.asyncIterator);

const rl2 = readline.createInterface({
  input: readStream2,
  crlfDelay: Infinity
})(Symbol.asyncIterator);

// https://www.codementor.io/@tiagolopesferreira/asynchronous-iterators-in-javascript-jl1yg8la1
// you can use result.value or also check result.done for end of stream
let line1 = rl1.next().value;
let line2 = rl2.next().value;

// compare line1 and line2
let result = line1 > line2 ? 1 : (line1 < line2 ? -1 : 0);

```
===========================
Actually, after writing this, I'm thinking about adding another lineReader that handle Stream and possibly a diffStream method.

```js
function myLineReader(readStream) {
  const rst = readline.createInterface({
    input: readStream,
    crlfDelay: Infinity
  })(Symbol.asyncIterator);

  rst.val = null;
  rst.nextVal = null;
  rst.lineNumber = -1;

  rst.moveNext = () => {
    rst.val = rst.nextVal;

    let nextResult = rst.next();
    rst.nextVal = nextResult.done ? false : nextResult.value;
    rst.lineNumber++;
    return rst.val;
  };

  // set current and next val
  rst.moveNext();
  rst.moveNext();

  return rst;
}
```

Not sure if I have time.  You're welcome to do a pull request.

**Comment by noogen** [comment]
Added diffStream in v1.3.0

**Comment by osher** [comment]
nice! I hope I'll soon get a task that requires to user it!
Keep up the good work!!

**Comment by osher** [comment]
mm. afterthought 

now it means that I can compare either 2 streams, or 2 files, but not a file and a stream. 
mm.

I can also propose to support option to ignore whitespace.

I'm rather over my head now with some stuff, I hope I can get back here later and contribute

**Comment by noogen** [comment]
Why not?  You can always create a stream from a file.  Then compare with your other stream.

```js
const readStream1 = fs.createReadStream(filename);
```

**Comment by noogen** [comment]
As for ignoring of white space, you can replace the default compare function with your own - https://github.com/niiknow/text-file-diff/blob/master/src/types.ts#L6

```js
  const m = new TextFileDiff({
    skipHeader: false,
    compareFn: function(l1, l2) {
       const line1 = `${l1}`.replace(/\s+/g, '');
       const line2 = `${l2}`.replace(/\s+/g, '');
       return line1 > line2 ? 1 : (line1 < line2 ? -1 : 0);
    }
  });
```

**Comment by noogen** [comment]
stale
